from django.db import models

class Category(models.Model):
        '''
    The category distincts the 2 different types of users, students and instructors.
    '''
    #either student or instructor
    user = models.CharField(max_length=20)
    
    
class Student(models.Model):
            '''
    The Student refers to an individual student, who is uniquely identified by a student_id-8 long string. It stores their name and their role through the category class
    '''
    #primary key of a student
    student_id = models.CharField(max_length=8, primary_key=True)
    
    #this is their name
    name = models.CharField(max_length=50)
    
    #foreign key reference to the Category
    category = models.ForeignKey(Category,on_delete=models.CASCADE,)
    

class Instructor(models.Model):
    '''
        The Instructor refers to an individual instructor who teaches on the college, who is uniquely identified with an integer. It stores their name and their role through the category class
    '''
    #automatically incremented id number
    id = models.AutoField(primary_key=True)
    
    #this is their name
    name = models.CharField(max_length=50)
    
    #foreign key reference to the Category
    category = models.ForeignKey(Category,on_delete=models.CASCADE,)
    
    
class Course(models.Model):
    '''
        The Course refers to an individual course offered by the college, who is uniquely identified with a combination of a department and an id number. It has information about the instructors who teach (might be more than one) the course and the students enrolled.
    '''
    #this is the department
    department = models.CharField(max_length=4)
    
    #this is the number of the course
    number = models.CharField(max_length=3)
    
    #many to many relationship of students and courses
    students = models.ManyToManyField(Student)
    
    #foreign key reference to the Instructor
    instructor = models.ForeignKey(Instructor,on_delete=models.CASCADE,)
    
class QR(models.Model):
    '''
        The QR refers to a code that was generated by an instructor for a specific class. It also contatins the time the code was generated.
    '''
    #unique code generated
    code = models.ImageField()
    
    #exact date/time the code was generated
    time = models.DateTimeField(auto_now_add=True)
    
    #foreign key reference to the Instructor
    instructor = models.ForeignKey(Instructor,on_delete=models.CASCADE,)
    
    #foreign key reference to the Course
    course = models.ForeignKey(Course,on_delete=models.CASCADE,)
    
class QRupload(models.Model):
    '''
        The QRupload refers to a code that was uploaded by a student for a specific class and it refers to a QR code that has been already generated by an instructor. It also contatins the time the code was uploaded.
    '''
    #foreign key reference to the QR
    code = models.ForeignKey(QR)
    
    #exact date/time the code was uploaded
    time = models.DateTimeField(auto_now_add=True)
    
    #foreign key reference to the Student
    student = models.ForeignKey(Student,on_delete=models.CASCADE,)
